#!/usr/bin/env node
// Compile the DTCG token source into CSS custom properties.
//
//   node skills/sites-design/scripts/compile-tokens.mjs
//
// - Top-level group names become CSS prefixes:  sp.4 -> --sp-4
// - The `semantic` group emits WITHOUT a prefix: semantic.bg -> --bg
// - "{group.token}" aliases resolve to var(--group-token)
// - "$extensions.dark" values are emitted in the dark blocks
//
// Zero dependencies. Deterministic output. Safe to run repeatedly.

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const tokenPath = resolve(here, "../assets/tokens/tokens.json");
const outPath = resolve(here, "../assets/tokens/tokens.css");

const ALIAS = /\{([^}]+)\}/g;
const aliasToVar = (s) =>
  String(s).replace(ALIAS, (_, path) => `var(--${path.replace(/\./g, "-")})`);

const isLeaf = (node) =>
  node && typeof node === "object" && Object.hasOwn(node, "$value");

function walk(node, path, visit) {
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith("$")) continue;
    const next = [...path, key];
    if (isLeaf(child)) visit(next, child);
    else if (child && typeof child === "object") walk(child, next, visit);
  }
}

function collect(group, { stripPrefix = false } = {}) {
  const rows = [];
  walk(group, [], (path, leaf) => {
    const name = (stripPrefix ? path : [group.__name, ...path]).join("-");
    rows.push({ name, value: aliasToVar(leaf.$value) });
  });
  return rows;
}

function block(rows, indent = "  ") {
  return rows.map((r) => `${indent}--${r.name}: ${r.value};`).join("\n");
}

const raw = JSON.parse(await readFile(tokenPath, "utf8"));
const root = [];
const dark = [];

for (const [key, value] of Object.entries(raw)) {
  if (key.startsWith("$")) continue;
  if (key === "semantic") {
    const g = { __name: "semantic" };
    Object.assign(g, value);
    root.push(...collect(g, { stripPrefix: true }));
    const darkRows = [];
    walk(value, [], (path, leaf) => {
      const v = leaf?.$extensions?.dark?.$value;
      if (v !== undefined) darkRows.push({ name: path.join("-"), value: aliasToVar(v) });
    });
    dark.push(...darkRows);
  } else {
    const g = { __name: key };
    Object.assign(g, value);
    root.push(...collect(g));
  }
}

const header = `/* GENERATED by skills/sites-design/scripts/compile-tokens.mjs
 * Source: skills/sites-design/assets/tokens/tokens.json
 * Do not edit by hand — edit the JSON and re-run the compiler. */`;

const css = `${header}

:root {
  color-scheme: light;
${block(root)}
}

@media (prefers-color-scheme: dark) {
  :root {
    color-scheme: dark;
${block(dark, "    ")}
  }
}

[data-theme="light"] {
  color-scheme: light;
${block(root)}
}

[data-theme="dark"] {
  color-scheme: dark;
${block(dark)}
}
`;

await writeFile(outPath, css, "utf8");
console.log(`wrote ${outPath} (${root.length} base, ${dark.length} dark tokens)`);
